on: 
  push 

jobs:
  get-artifact-list:
    runs-on: ubuntu-latest
    steps:
      - name: get the list
        run: |
         git clone https://github.com/kata-containers/packaging kata-packaging
         pushd kata-packaging
         tag=`echo $GITHUB_REF | cut -d/ -f3-`
         git checkout master
         popd
         ./kata-packaging/artifact-list.sh > artifact-list.txt
         cat artifact-list.txt
      - name: save-artifact-list
        uses: actions/upload-artifact@master
        with: 
          name: artifact-list 
          path: artifact-list.txt
  build-kernel:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    steps:
      - uses: actions/checkout@v1
      - name: get-artifact-list
        uses: actions/download-artifact@master
        with:
          name: artifact-list
      - name: build-kernel
        run: |
         if grep -q "install_kernel" ./artifact-list/artifact-list.txt; then
           ls -la $GITHUB_WORKSPACE
           .github/workflows/generate-artifact-tarball.sh "install_kernel" $GITHUB_REF
           # install kernel dependencies
           sudo apt-get update && sudo apt install -y flex bison libelf-dev bc iptables
           export GOPATH=$HOME/go
           go get github.com/kata-containers/packaging || true
           pushd $GOPATH/src/github.com/kata-containers/packaging/release >>/dev/null
           # Get versions information
           tag=`echo $GITHUB_REF | cut -d/ -f3-`
           git checkout $tag
           pushd ../obs-packaging
           ./gen_versions_txt.sh $tag
           popd
           # Build the kernel:
           source ./kata-deploy-binaries.sh
           install_kernel
           echo ::set-env name=artifact-built::true
           popd >>/dev/null
           mv $HOME/go/src/github.com/kata-containers/packaging/release/kata-kernel.tar.gz .
         else
           echo ::set-env name=artifact-built::false
         fi
      - name: store-artifacts
        if: env.artifact-built == 'true' 
        uses: actions/upload-artifact@master
        with: 
          name: kata-artifacts
          path: kata-kernel.tar.gz
