# When a release page is published, start the release artifact process
on: release
name: Build, Test, and Publish kata-deploy

jobs:
  # create image and upload to release page (can we get branch information from release tag?
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name : the ok ok 
      run: |  
        echo "hello worold"
        sudo apt-get update
        sudo apt-get install -y docker-ce git
        echo "still?"
        git clone https://github.com/kata-containers/packaging
        cd packaging
        echo `pwd`
        echo "done...."
